### ISSUE TITLE
Module compatibility with puppet 5

### ISSUE THREAD

**Issue by truthbk** [puppetlabs/puppetlabs-puppetserver_gem#20]
Hi, 

I actually _think_, but correct me if I'm wrong, that this module is actually compatible with puppet 5. The metadata suggests otherwise. If it is indeed incompatible, or not recommended, what would you recommend we use to use gems on the puppet server side? Otherwise, can the metadata be updated? 

Thanks!

**Comment by tkishel** [comment]
Version 1.1.0 is compatible with:

Puppet Enterprise 2019.0.x, 2018.1.x, 2017.3.x, 2017.2.x, 2017.1.x, 2016.5.x, 2016.4.x
Puppet >=4.0.0 < 7.0.0

**Comment by tkishel** [comment]
Resolved!
