### ISSUE TITLE
git tags are not in sync with the module version

### ISSUE THREAD

**Issue by cremenyi** [puppetlabs/puppetlabs-puppetserver_gem#28]
Could you please tag the git repository to be in sync with the module version?

**Comment by keirans** [comment]
+1 here.

This makes things extremely challenging for environments that don't have direct access to the forge and use git mirrors for module deployment.

**Comment by seanmil** [comment]
+1 here as well. We rely on git mirrors.

**Comment by tkishel** [comment]
https://github.com/puppetlabs/puppetlabs-puppetserver_gem/tree/1.1.1
