### ISSUE TITLE
A bit ..... slow?

### ISSUE THREAD

**Issue by earsdown** [puppetlabs/puppetlabs-puppetserver_gem#9]
So....uhm.. `puppetserver gem` is around 10x slower than other gem providers. Howcome?

``` console
[root@puppet ~]# time puppet resource package hiera-eyaml-gpg provider=puppetserver_gem
package { 'hiera-eyaml-gpg':
  ensure => ['0.6'],
}

real    0m41.926s
user    0m40.222s
sys 0m1.183s

[root@puppet ~]# time puppet resource package hiera-eyaml-gpg provider=puppet_gem
package { 'hiera-eyaml-gpg':
  ensure => ['0.6'],
}

real    0m4.374s
user    0m3.862s
sys 0m0.389s
[root@puppet03 ~]#
```

**Comment by vinzent** [comment]
puppetserver is jruby, jruby has slow startup.

**Comment by tkishel** [comment]
This has been addressed by https://github.com/puppetlabs/puppetlabs-puppetserver_gem/pull/24 for all but instaling and removing puppetserver gems.

**Comment by tkishel** [comment]
Improved by #24 which uses an alternative to JRuby to list gems.
Not worth the risk to install gems, but once gems are installed, only list is executed.
